server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    
bigcatai:
  openai.client.config:
      onnection-timout: 60
      read_timeout: 120
      completions-api-endpoint-url: https://api.openai.com/v1/completions
      embeddings-api-endpoint-url: https://api.openai.com/v1/embeddings 
      chat-completions-api-endpoint-url: https://api.openai.com/v1/chat/completions
      api-key: ${bigcatai.openai.client.config.api-key}
  vector-database.config:
      type: MEMORY #REDIS
      #redis-host: localhost
      #redis-port: 6379
      data-file-path: data/vector-store.txt